### ISSUE TITLE
Getting "GitHub Actions is not permitted to create or approve pull requests." error

### ISSUE THREAD

**Issue by rubenmamo** [vic1707/GHA-combine-PRs#46]
Is it normal to get the below error when running this action? Am I missing something obvious?

```
RequestError [HttpError]: GitHub Actions is not permitted to create or approve pull requests.
    at /home/runner/work/_actions/vic1707/GHA-combine-PRs/1.1.0/dist/index.js:1:121233
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async manageCombinePR (/home/runner/work/_actions/vic1707/GHA-combine-PRs/1.1.0/dist/index.js:7:4[26](https://github.com/R150-Software/LeagueManager-App/actions/runs/4474456851/jobs/7862941180#step:2:27)758)
    at async run (/home/runner/work/_actions/vic1707/GHA-combine-PRs/1.1.0/dist/index.js:7:431231) {
  status: 403,
```

**Comment by vic1707** [comment]
Hello,
I'm sorry I've never seen this error, maybe your repo has some rules/permissions on who can create PRs?
